{
 "title": "Laminazione",
 "time": { "from": "2024-04-05T07:28:40.012Z", "to": "2024-04-05T07:44:09.630Z" },
 "refresh": "5s",
 "panels": [
  { "title": "FORNO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT COUNT(ID_ordine) FROM Laminazione.dbo.ORDINI WHERE stato_ordine =1"
    }
   ]
  },
  {
   "title": "PIANO DI CARICA",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 1 },
   "options": {
    "content": "<table width=100% style='border:2px solid green'>\n  <tr>\n    <td style='border:0; background-color: green ; font-size:18px'>ordine:\n      <b style='font-size:20px'>\n      {{ID_ordine}}\n        </b>\n    </td>\n    <td style='border:0; text-align:center'>rimanenti:\n      <b style= 'font-size:20px'>\n      {{rimanenti}}\n      </b>\n    </td>\n    <td style='border:0; text-align:right'>bill totali:\n      <b style='font-size:20px'>\n      {{n_billette}}\n      </b>\n    </td>\n  </tr>\n  <tr>\n    <td style='border:0'>lunghezza:\n      {{lunghezza}}\n    </td>\n    <td style='border:0; text-align:center'>sezione:\n      {{sezione}}\n    </td>\n    <td style='border:0; text-align:center'>materiale:\n      {{materiale}}\n    <td style='border:0; text-align:center'>data_creazione:\n      {{date creazione 'DD MMM YYYY'}}\n    </td>\n  </tr>\n</table>"
   },
   "targets": [
    {
     "rawSql": "SELECT ID_ordine, lunghezza, sezione, materiale, \r\ndata_creazione at time zone 'Central European Standard Time' , \r\n(n_billette- n_bill_pesate) as rimanenti, n_billette FROM dbo.ORDINI \r\nWHERE stato_ordine = 1 "
    }
   ]
  },
  {
   "title": "INFORNAMENTO",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "<table width=100% style='border:2px solid #bdb76b'>\n  <tr>\n    <td style='border:0; background-color: #bdb76b ; color:black; font-size:18px'>ordine:\n      <b style='font-size:20px; color:black'>\n      {{ID_ordine}}\n        </b>\n    </td>\n    <td style='border:0; text-align:center'>sforn:\n      <b style= 'font-size:20px'>\n      {{sforn}}\n      </b>\n    </td>\n    <td style='border:0; text-align:right'>inforn:\n      <b style='font-size:20px'>\n      {{inforn}}\n      </b>\n    </td>\n    <td style='border:0; text-align:center'>pesa:\n      <b style='font-size:20px'>\n      {{pesa}}\n      </b>\n    </td>\n    <td style='border:0'>prev:\n      <b style='font-size:20px'>\n      {{prev}}\n      </b>\n    </td>\n  </tr>\n  <tr>\n    <td style='border:0'>lunghezza:\n      {{lunghezza}}\n    </td>\n    <td style='border:0'>sezione:\n      {{sezione}}\n    </td>\n    <td style='border:0; text-align:center'>materiale:\n      {{materiale}}\n    <td style='border:0; text-align:center'>data_creazione:\n      {{date creazione 'DD MMM YYYY'}}\n    </td>\n  </tr>\n</table>"
   },
   "targets": [
    {
     "rawSql": "SELECT ID_ordine, lunghezza, sezione, materiale, data_creazione at time zone 'Central European Standard Time' as creazione, n_bill_sfornate as sforn, n_bill_infornate as inforn, n_bill_pesate as pesa, n_billette as prev\r\nFROM dbo.ORDINI \r\nWHERE ID_ordine = (SELECT TOP 1 ID_ordine FROM dbo.BILLETTE WHERE ID_billetta = (\r\nSELECT TOP 1 ID_billetta FROM BILLETTE WHERE stato_billetta = 3 ORDER BY ID_billetta DESC))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT COUNT (ID_billetta)-(\r\nSELECT sum(n_bill_pesate) FROM dbo.ORDINI WHERE ID_ordine IN (SELECT ID_ordine FROM dbo.ORDINI WHERE stato_ordine =1 ) )\r\nFROM dbo.BILLETTE  WHERE ID_ordine IN \r\n(SELECT id_ordine FROM dbo.ORDINI WHERE stato_ordine = 1)"
    }
   ]
  },
  {
   "title": "NEL FORNO",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "options": {
    "content": "<table width=100% style='border:2px solid #a52a2a'>\n  <tr>\n    <td style='border:0; background-color: #a52a2a ; color:black; font-size:18px'>ordine:\n      <b style='font-size:20px; color:black'>\n      {{ID_ordine}}\n        </b>\n    </td>\n    <td style='border:0; text-align:center'>sforn:\n      <b style= 'font-size:20px'>\n      {{sforn}}\n      </b>\n    </td>\n    <td style='border:0; text-align:right'>inforn:\n      <b style='font-size:20px'>\n      {{inforn}}\n      </b>\n    </td>\n    <td style='border:0; text-align:center'>pesa:\n      <b style='font-size:20px'>\n      {{pesa}}\n      </b>\n    </td>\n    <td style='border:0'>prev:\n      <b style='font-size:20px'>\n      {{prev}}\n      </b>\n    </td>\n  </tr>\n  <tr>\n    <td style='border:0'>lunghezza:\n      {{lunghezza}}\n    </td>\n    <td style='border:0'>sezione:\n      {{sezione}}\n    </td>\n    <td style='border:0; text-align:center'>materiale:\n      {{materiale}}\n    <td style='border:0; text-align:center'>data_creazione:\n      {{date creazione 'DD MMM YYYY'}}\n    </td>\n  </tr>\n</table>"
   },
   "targets": [
    {
     "rawSql": "SELECT ID_ordine, lunghezza, sezione, materiale, data_creazione at time zone 'Central European Standard Time' as creazione, n_bill_sfornate as sforn, n_bill_infornate as inforn, n_bill_pesate as pesa, n_billette as prev \r\nFROM dbo.ORDINI \r\nWHERE ID_ordine IN (SELECT ID_ordine FROM dbo.BILLETTE WHERE ID_billetta IN (\r\nSELECT ID_billetta FROM BILLETTE WHERE stato_billetta = 3))"
    }
   ]
  },
  {
   "title": "PESO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT  top 1 peso FROM Laminazione.dbo.BILLETTE WHERE stato_billetta = 2 ORDER BY ID_billetta DESC"
    }
   ]
  },
  {
   "title": "PESA",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 10, "x": 2, "y": 6 },
   "options": {
    "content": "<table width=100% style='border:2px solid \t#db7093'>\n  <tr>\n    <td style='border:0; background-color: \t#db7093; color: black;font-size:18px; text-align:center'>billetta:\n      <p style margin:0>\n        <b style='font-size:20px;color:black'>\n      {{ID_billetta}}\n        </b>\n      </p>\n    </td>\n    <td style='border:0; text-align:center'>ordine:\n      <b style='font-size:20px'>\n       {{ID_ordine}}\n     </b>\n    </td>\n    <td style='border:0; text-align:center'>bill in pesa:\n      <b style='font-size:20px'>\n      {{bill_in_pesa}}\n      </b>\n    </td>\n    <td style='border:0 ;text-align:center'>prev:\n      <b style='font-size:20px'>\n      {{prev}}\n      </b>\n    </td>\n  </tr>\n</table>"
   },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT\r\n  b.ID_ordine as ID_ordine,\r\n  ID_billetta,\r\n  n_bill_pesate as bill_in_pesa,\r\n  n_billette as prev\r\nFROM\r\n  dbo.BILLETTE as b\r\n  JOIN dbo.ORDINI as o ON (b.ID_ordine = o.ID_ordine)\r\nWHERE\r\n  b.stato_billetta = 2"
    }
   ]
  },
  {
   "title": "FOTO",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    { "path": "img" }
   ]
  },
  {
   "title": "LETTURA QR CODE",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 10 },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as v_1 FROM UTILITY WHERE ID_utility = 1 "
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as v_2 FROM UTILITY WHERE ID_utility = 1 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT COUNT (id_billetta) FROM Laminazione.dbo.BILLETTE WHERE stato_billetta = 3"
    }
   ]
  },
  { "title": "TRACKING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "SFORNATE",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "options": {
    "content": "<table width=100% style='border:2px solid #9370db'>\n  <tr>\n    <td style='border:0; background-color: #9370db ; color:black; font-size:18px'>ordine:\n      <b style='font-size:20px; color:black'>\n      {{ID_ordine}}\n        </b>\n    </td>\n    <td style='border:0; text-align:center'>lami:\n      <b style= 'font-size:20px'>\n      {{lami}}\n      </b>\n    </td>\n    <td style='border:0; text-align:right'>sforn:\n      <b style='font-size:20px'>\n      {{sforn}}\n      </b>\n    </td>\n    <td style='border:0; text-align:center'>inforn:\n      <b style='font-size:20px'>\n      {{inforn}}\n      </b>\n    </td>\n    <td style='border:0'>prev:\n      <b style='font-size:20px'>\n      {{prev}}\n      </b>\n    </td>\n  </tr>\n  <tr>\n    <td style='border:0'>lunghezza:\n      {{lunghezza}}\n    </td>\n    <td style='border:0'>sezione:\n      {{sezione}}\n    </td>\n    <td style='border:0; text-align:center'>materiale:\n      {{materiale}}\n    <td style='border:0; text-align:center'>data_creazione:\n      {{date creazione 'DD MMM YYYY'}}\n    </td>\n  </tr>\n</table>"
   },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ID_ordine,\r\n  lunghezza,\r\n  sezione,\r\n  materiale,\r\n  data_creazione at time zone 'Central European Standard Time' as creazione,\r\n  n_bill_laminate as lami,\r\n  n_bill_sfornate as sforn,\r\n  n_bill_infornate as inforn,\r\n \r\n  n_billette as prev\r\nFROM\r\n  dbo.ORDINI\r\nWHERE\r\n  ID_ordine IN (\r\n    SELECT\r\n      ID_ordine\r\n    FROM\r\n      dbo.BILLETTE\r\n    WHERE\r\n      ID_billetta IN (\r\n        SELECT\r\n          ID_billetta\r\n        FROM\r\n          BILLETTE\r\n        WHERE\r\n          stato_billetta = 4\r\n      )\r\n  )"
    }
   ]
  },
  {
   "title": "IN LAMINAZIONE",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "options": {
    "content": "<table width=100% style='border:2px solid \t#4682b4'>\n  <tr>\n    <td style='border:0; background-color: \t#4682b4; color: black;font-size:18px; text-align:center'>billetta:\n      <p style margin:0>\n        <b style='font-size:20px;color:black'>\n      {{ID_billetta}}\n        </b>\n      </p>\n    </td>\n    <td style='border:0; text-align:center'>ordine:\n      <b style='font-size:20px'>\n       {{ID_ordine}}\n     </b>\n    </td>\n    <td style='border:0; text-align:center'>materiale:\n      <b style='font-size:20px'>\n      {{materiale}}\n      </b>\n    </td>\n    <td style='border:0 ;text-align:center'>lami:\n      <b style='font-size:20px'>\n      {{lami}}\n      </b>\n    </td>\n    <td style='border:0 ;text-align:center'>prev:\n      <b style='font-size:20px'>\n          {{prev}}\n          </b>\n    </td>\n  </tr>\n</table>"
   },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT\r\n  b.ID_ordine as ID_ordine,\r\n  ID_billetta,\r\n  materiale,\r\n  n_bill_laminate as lami,\r\n  n_billette as prev\r\nFROM\r\n  dbo.BILLETTE as b\r\n  JOIN dbo.ORDINI as o ON (b.ID_ordine = o.ID_ordine)\r\nWHERE\r\n  b.stato_billetta = 5"
    }
   ]
  },
  {
   "title": "TRENO",
   "type": "canvas",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "Node-red",
     "rawSql": "SELECT valore as TAG_1 FROM dbo.GABBIE WHERE ID_gabbia = 1"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as TAG_2 FROM dbo.GABBIE WHERE ID_gabbia = 2"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as TAG_3 FROM dbo.GABBIE WHERE ID_gabbia = 3"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as TAG_4 FROM dbo.GABBIE WHERE ID_gabbia = 4"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as TAG_5 FROM dbo.GABBIE WHERE ID_gabbia = 5"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as TAG_6 FROM dbo.GABBIE WHERE ID_gabbia = 6"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as TAG_7 FROM dbo.GABBIE WHERE ID_gabbia = 7"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as TAG_8 FROM dbo.GABBIE WHERE ID_gabbia = 8"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as TAG_9 FROM dbo.GABBIE WHERE ID_gabbia = 9"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as TAG_10 FROM dbo.GABBIE WHERE ID_gabbia = 10"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore FROM dbo.UTILITY WHERE ID_utility = 2"
    }
   ]
  },
  {
   "title": "ORDINI LAMINATI",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 32 },
   "options": {
    "content": "<table width=100% style='border:2px solid #008080'>\n  <tr>\n    <td style='border:0; background-color: #008080 ; font-size:18px'>ordine:\n      <b style='font-size:20px'>\n      {{ID_ordine}}\n        </b>\n    </td>\n    <td style='border:0; text-align:center'>bill totali:\n      <b style='font-size:20px'>\n      {{bill}}\n      </b>\n    </td>\n    <td style='border:0; text-align:center'>data_fine:\n      {{date fine 'DD MMM YYYY'}}\n    </td>\n  </tr>\n  <tr>\n    <td style='border:0'>lunghezza:\n      {{lunghezza}}\n    </td>\n    <td style='border:0; text-align:center'>sezione:\n      {{sezione}}\n    </td>\n    <td style='border:0; text-align:center'>materiale:\n      {{materiale}}\n  </tr>\n</table>"
   },
   "targets": [
    {
     "rawSql": " SELECT\r\n  ID_ordine,\r\n  lunghezza,\r\n  sezione,\r\n  materiale,\r\n  data_fine as fine,\r\n  n_billette as bill\r\nFROM\r\n  dbo.ORDINI\r\nWHERE\r\n  stato_ordine = 5"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(ID_billetta) FROM BILLETTE WHERE stato_billetta = 4"
    }
   ]
  },
  {
   "title": "VELOCITA LAMINAZIONE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "rawSql": "SELECT valore/10.0 FROM Laminazione.dbo.UTILITY WHERE ID_utility= 3"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(ID_billetta) FROM BILLETTE WHERE stato_billetta = 6"
    }
   ]
  },
  { "title": "GABBIE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "ST 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as stato, usura as lavorabili, riduzione FROM dbo.GABBIE WHERE ID_gabbia =1 "
    }
   ]
  },
  {
   "title": "ST 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as stato, usura as lavorabili, riduzione FROM dbo.GABBIE WHERE ID_gabbia = 2"
    }
   ]
  },
  {
   "title": "ST 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as stato, usura as lavorabili, riduzione FROM dbo.GABBIE WHERE ID_gabbia = 3"
    }
   ]
  },
  {
   "title": "ST 4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as stato, usura as lavorabili, riduzione FROM dbo.GABBIE WHERE ID_gabbia = 4"
    }
   ]
  },
  {
   "title": "SCORE ST 1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT ((usura*100)/20000000) as perc FROM dbo.GABBIE WHERE ID_gabbia = 1"
    }
   ]
  },
  {
   "title": "SCORE ST 2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT ((usura*100)/20000000) as perc FROM dbo.GABBIE WHERE ID_gabbia = 2"
    }
   ]
  },
  {
   "title": "SCORE ST 3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT ((usura*100)/20000000) as perc FROM dbo.GABBIE WHERE ID_gabbia = 3"
    }
   ]
  },
  {
   "title": "SCORE ST 4",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT ((usura*100)/20000000) as perc FROM dbo.GABBIE WHERE ID_gabbia = 4"
    }
   ]
  },
  {
   "title": "ST 5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as stato, usura as lavorabili, riduzione FROM dbo.GABBIE WHERE ID_gabbia = 5"
    }
   ]
  },
  {
   "title": "ST 6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as stato, usura as lavorabili, riduzione FROM dbo.GABBIE WHERE ID_gabbia = 6"
    }
   ]
  },
  {
   "title": "ST 7",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as stato, usura as lavorabili, riduzione FROM dbo.GABBIE WHERE ID_gabbia = 7"
    }
   ]
  },
  {
   "title": "ST 8",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as stato, usura as lavorabili, riduzione FROM dbo.GABBIE WHERE ID_gabbia = 8"
    }
   ]
  },
  {
   "title": "SCORE ST 5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT ((usura*100)/20000000) as perc FROM dbo.GABBIE WHERE ID_gabbia = 5"
    }
   ]
  },
  {
   "title": "SCORE ST 6",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT ((usura*100)/20000000) as perc FROM dbo.GABBIE WHERE ID_gabbia = 6"
    }
   ]
  },
  {
   "title": "SCORE ST 7",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT ((usura*100)/20000000) as perc FROM dbo.GABBIE WHERE ID_gabbia = 7"
    }
   ]
  },
  {
   "title": "SCORE ST 8",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT ((usura*100)/20000000) as perc FROM dbo.GABBIE WHERE ID_gabbia = 8"
    }
   ]
  },
  {
   "title": "ST 9",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as stato, usura as lavorabili, riduzione FROM dbo.GABBIE WHERE ID_gabbia = 9"
    }
   ]
  },
  {
   "title": "ST 10",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as stato, usura as lavorabili, riduzione FROM dbo.GABBIE WHERE ID_gabbia = 10"
    }
   ]
  },
  {
   "title": "ALLARMI",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    { "dataset": "Laminazione" }
   ]
  },
  {
   "title": "SCORE ST 9",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT ((usura*100)/20000000) as perc FROM dbo.GABBIE WHERE ID_gabbia = 9"
    }
   ]
  },
  {
   "title": "SCORE ST 10",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT ((usura*100)/20000000) as perc FROM dbo.GABBIE WHERE ID_gabbia = 10"
    }
   ]
  },
  { "title": "STATISTICHE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "BILLETTE LAMINATE NEL TEMPO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 64 },
   "targets": [
    {
     "dataset": "Node-red",
     "rawSql": "\r\nSELECT  [data_sfornamento] at time zone 'Central European Standard Time', peso_prod_finito\r\n  FROM [dbo].[BILLETTE]\r\n  WHERE ID_billetta IN (SELECT ID_billetta FROM BILLETTE WHERE stato_billetta = 6)\r\n  GROUP BY data_sfornamento, peso_prod_finito\r\n"
    }
   ]
  },
  {
   "title": "DISPONIBILITA'",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT (valore/24.0)*100 as disponibilità FROM Laminazione.dbo.UTILITY WHERE ID_utility= 4\r\n"
    }
   ]
  },
  {
   "title": "PRESTAZIONI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT (valore/1140.0)*100 FROM Laminazione.dbo.UTILITY WHERE ID_utility= 5"
    }
   ]
  },
  {
   "title": "QUALITA'",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT AVG (qualita), CONVERT(date, data_fine AT TIME ZONE 'Central European Standard Time') as data_fine\r\nFROM ORDINI\r\nWHERE stato_ordine = 5\r\n AND  $__timeFilter(data_fine) \r\nGROUP BY CONVERT(date, data_fine AT TIME ZONE 'Central European Standard Time')\r\n"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT (\r\n(SELECT (valore/1140.0) FROM Laminazione.dbo.UTILITY WHERE ID_utility= 5)*\r\n(SELECT (valore/24.0) FROM Laminazione.dbo.UTILITY WHERE ID_utility= 4)*\r\n(SELECT (AVG (qualita))/100\r\nFROM ORDINI\r\nWHERE stato_ordine = 5\r\n  AND  $__timeFilter(data_fine)) *100 )as OEE"
    }
   ]
  },
  {
   "title": "TEMPO DI FERMO",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as guasti FROM UTILITY WHERE ID_utility = 6 "
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as manutenzione FROM UTILITY WHERE ID_utility = 7"
    },
    {
     "dataset": "Laminazione",
     "rawSql": "SELECT valore as avviamento FROM UTILITY WHERE ID_utility = 8"
    }
   ]
  },
  {
   "title": "TONNELLATE LAMINATE",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "kg" } },
   "targets": [
    {
     "dataset": "Node-red",
     "rawSql": "\r\nSELECT SUM(peso_prod_finito) as tonnellate, \r\n       CONVERT(date, data_uscita AT TIME ZONE 'Central European Standard Time') \r\nFROM [dbo].[BILLETTE]\r\nWHERE stato_billetta = 6\r\nAND  $__timeFilter(data_uscita) \r\nGROUP BY CONVERT(date, data_uscita AT TIME ZONE 'Central European Standard Time')\r\n"
    }
   ]
  },
  {
   "title": "BILLETTELAMINATE",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "dataset": "Node-red",
     "rawSql": "\r\nSELECT  COUNT(ID_billetta) as totale, CONVERT(date, data_uscita AT TIME ZONE 'Central European Standard Time') as data_uscita\r\n  FROM [dbo].[BILLETTE]\r\nWHERE stato_billetta = 6\r\n AND   $__timeFilter(data_uscita)\r\nGROUP BY CONVERT(date, data_uscita AT TIME ZONE 'Central European Standard Time')\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "ORDINI LAMINATI",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "dataset": "Node-red",
     "rawSql": "\r\nSELECT  COUNT(DISTINCT (ID_ordine)) as totale, CONVERT(date, data_fine AT TIME ZONE 'Central European Standard Time') \r\n  FROM [dbo].ORDINI\r\nWHERE stato_ordine = 5\r\n  AND  $__timeFilter(data_fine) \r\nGROUP BY CONVERT(date, data_fine AT TIME ZONE 'Central European Standard Time')\r\n\r\n\r\n\r\n"
    }
   ]
  }
 ]
}